version: '3.8'

services:

  permission_api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - '8085:8085'
    environment:
      POSTGRES_HOST: permission_db
      POSTGRES_DB: p_db
      POSTGRES_USER: p_user
      POSTGRES_PASSWORD: p_password
      POSTGRES_PORT: 5432
    depends_on:
      - permission_db

  permission_db:
    image: postgres:15
    environment:
      POSTGRES_DB: p_db
      POSTGRES_USER: p_user
      POSTGRES_PASSWORD: p_password
    ports:
      - "5435:5432"
    volumes:
      - p_db_data:/var/lib/postgresql/data

volumes:
  p_db_data:
    external: false
